issue_templates:
  - name: "Bug report"
    description: "Report a bug"
    url: "https://github.com/masutakanet/.github/blob/main/.github/ISSUE_TEMPLATE/1.Bug_report.yml"
    labels: ["bug"]
contact_links:
  - name: Feature request
    url: https://github.com/masutakanet/sandbox/discussions/categories/ideas
    about: Share ideas for new features
  - name: Ask a question
    url: https://github.com/masutakanet/sandbox/discussions/categories/q-a
    about: Ask questions and discuss with other community members
